[package]
name = "blind-proxy-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
blind-wrapper-rs = { path = "../blind-wrapper-rs" }
clap = { version = "4.5.38", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
