/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePassword {
    #[serde(rename = "old_password")]
    pub old_password: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "password_confirm")]
    pub password_confirm: String,
}

impl ChangePassword {
    pub fn new(old_password: String, password: String, password_confirm: String) -> ChangePassword {
        ChangePassword {
            old_password,
            password,
            password_confirm,
        }
    }
}

