/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CsrfRetrieve200Response {
    #[serde(rename = "csrfToken", skip_serializing_if = "Option::is_none")]
    pub csrf_token: Option<String>,
}

impl CsrfRetrieve200Response {
    pub fn new() -> CsrfRetrieve200Response {
        CsrfRetrieve200Response {
            csrf_token: None,
        }
    }
}

