/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DefaultSendResetPasswordLink : Default serializer used for sending reset password link.  It will use :ref:`send-reset-password-link-serializer-use-email-setting` setting.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultSendResetPasswordLink {
    #[serde(rename = "email")]
    pub email: String,
}

impl DefaultSendResetPasswordLink {
    /// Default serializer used for sending reset password link.  It will use :ref:`send-reset-password-link-serializer-use-email-setting` setting.
    pub fn new(email: String) -> DefaultSendResetPasswordLink {
        DefaultSendResetPasswordLink {
            email,
        }
    }
}

