/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DefaultRegisterEmail : Default serializer used for e-mail registration (e-mail change).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultRegisterEmail {
    #[serde(rename = "email")]
    pub email: String,
}

impl DefaultRegisterEmail {
    /// Default serializer used for e-mail registration (e-mail change).
    pub fn new(email: String) -> DefaultRegisterEmail {
        DefaultRegisterEmail {
            email,
        }
    }
}

