/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Grant : HyperlinkedModelSerializer with `id` as the first field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Grant {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "organization")]
    pub organization: String,
    #[serde(rename = "teams")]
    pub teams: Vec<String>,
    /// A human-readable name for this grant.
    #[serde(rename = "name")]
    pub name: String,
    /// The codename for this grant.
    #[serde(rename = "codename")]
    pub codename: String,
    /// Field names of keys to request. None means allows all fields & query key; or a mapping of specific field names: `{'field_name': True, ...}`
    #[serde(rename = "field_names", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub field_names: Option<Option<serde_json::Value>>,
    /// Whether this permission allows the user to share the key(s) assigned to this permission.
    #[serde(rename = "can_share_keys", skip_serializing_if = "Option::is_none")]
    pub can_share_keys: Option<bool>,
    /// Whether this permission allows the user to create records.
    #[serde(rename = "can_create_records", skip_serializing_if = "Option::is_none")]
    pub can_create_records: Option<bool>,
    /// The dataset that this grant belongs to.
    #[serde(rename = "dataset")]
    pub dataset: String,
    /// The schema that this grant belongs to.
    #[serde(rename = "schema")]
    pub schema: String,
}

impl Grant {
    /// HyperlinkedModelSerializer with `id` as the first field.
    pub fn new(id: String, url: String, organization: String, teams: Vec<String>, name: String, codename: String, dataset: String, schema: String) -> Grant {
        Grant {
            id,
            url,
            organization,
            teams,
            name,
            codename,
            field_names: None,
            can_share_keys: None,
            can_create_records: None,
            dataset,
            schema,
        }
    }
}

