/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexedRecord : Serializer for creating a Record and creating the schema index values together.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexedRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "schema")]
    pub schema: String,
    #[serde(rename = "hashed_label_map")]
    pub hashed_label_map: std::collections::HashMap<String, models::IndexedRecordHashedLabelMapValue>,
    /// The data that this record represents.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl IndexedRecord {
    /// Serializer for creating a Record and creating the schema index values together.
    pub fn new(id: String, url: String, schema: String, hashed_label_map: std::collections::HashMap<String, models::IndexedRecordHashedLabelMapValue>) -> IndexedRecord {
        IndexedRecord {
            id,
            url,
            schema,
            hashed_label_map,
            data: None,
        }
    }
}

