/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsUpload200Response {
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<uuid::Uuid>,
}

impl JobsUpload200Response {
    pub fn new() -> JobsUpload200Response {
        JobsUpload200Response {
            job_id: None,
        }
    }
}

