/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Logout {
    #[serde(rename = "revoke_token", skip_serializing_if = "Option::is_none")]
    pub revoke_token: Option<bool>,
}

impl Logout {
    pub fn new() -> Logout {
        Logout {
            revoke_token: None,
        }
    }
}

