/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MaterialProof : Proof for a material.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterialProof {
    /// Proof for the material.
    #[serde(rename = "proof")]
    pub proof: String,
}

impl MaterialProof {
    /// Proof for a material.
    pub fn new(proof: String) -> MaterialProof {
        MaterialProof {
            proof,
        }
    }
}

