/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationUpdate : Update an Organization, allowing for the owner to be changed.  Since an Owner is a 1:1 relationship, we can't use the default `NestedHyperlinkedRelatedField` and must change it to an `OrganizationUser` queryset limited to organization members.  The `to_representation()` method is overloaded to return the correct URL for the owner.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationUpdate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "organization_users")]
    pub organization_users: Vec<String>,
    /// A unique ID used to identify this organization
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// A human-readable name for this organization
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "modified")]
    pub modified: String,
}

impl OrganizationUpdate {
    /// Update an Organization, allowing for the owner to be changed.  Since an Owner is a 1:1 relationship, we can't use the default `NestedHyperlinkedRelatedField` and must change it to an `OrganizationUser` queryset limited to organization members.  The `to_representation()` method is overloaded to return the correct URL for the owner.
    pub fn new(id: String, url: String, owner: String, organization_users: Vec<String>, name: String, created: String, modified: String) -> OrganizationUpdate {
        OrganizationUpdate {
            id,
            url,
            owner,
            organization_users,
            slug: None,
            name,
            is_active: None,
            created,
            modified,
        }
    }
}

