/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRefresh {
    #[serde(rename = "access")]
    pub access: String,
    #[serde(rename = "refresh")]
    pub refresh: String,
}

impl TokenRefresh {
    pub fn new(access: String, refresh: String) -> TokenRefresh {
        TokenRefresh {
            access,
            refresh,
        }
    }
}

