/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenObtainPair {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "access")]
    pub access: String,
    #[serde(rename = "refresh")]
    pub refresh: String,
}

impl TokenObtainPair {
    pub fn new(email: String, password: String, access: String, refresh: String) -> TokenObtainPair {
        TokenObtainPair {
            email,
            password,
            access,
            refresh,
        }
    }
}

