/*
 * Blind Insight REST API
 *
 * End-to-end encrypted datastore
 *
 * The version of the OpenAPI document: 10.6.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenVerify {
    #[serde(rename = "token")]
    pub token: String,
}

impl TokenVerify {
    pub fn new(token: String) -> TokenVerify {
        TokenVerify {
            token,
        }
    }
}

